### ISSUE TITLE
Unallocated pointer free attempt

### ISSUE THREAD

**Issue by pipboy96** [cschanaj/xhttpse2#15] opened 2020-04-15 11:08 UTC
Running xhttpse2 with ~~this list~~ consistently causes a `pointer being freed was not allocated` error.

**Comment by cschanaj** [comment] 2020-05-01 04:32
While I cannot reproduce this, I suspect this is related to a memory leak issue fixed in #19. Would you try again with the current `master` branch?

**Closed as completed** 2020-05-30 20:10 UTC
